security:
    providers:
        in_memory:
            memory:
                users:
                    api:
                        password: '%env(API_PASSWORD)%'
                        roles: 'ROLE_API'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext
#            algorithm: bcrypt
#            cost: 10

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login_check
            stateless: true
            anonymous: true
            provider: in_memory
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true

    access_control:
#        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
