parameters:

services:
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']
#        bind:
#            $appName: 'Gyro'

#    App\UI\Command\:
#        resource: '../src/UI/Command'
#        autowire: true
#        autoconfigure: true

#    App\Infrastructure\:
#        resource: '../src/Infrastructure'
#        autowire: true
#        autoconfigure: true
